In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt

In [2]:
class AttentionLayer(nn.Module):
    def __init__(self, q, k, v, device='cpu'):
        super(AttentionLayer, self).__init__()
        self.q = torch.tensor(q, requires_grad=True, device=device)
        self.k = torch.tensor(k, requires_grad=True, device=device)
        self.m = torch.ones_like(k)
        self.m[self.k==1] = 0
        self.v = torch.tensor(v, requires_grad=True, device=device)
    def forward(self):
        pass
        print('in')
        kq = torch.bmm(torch.transpose(self.k, 1,2), self.q)
        sm = F.softmax(kq, dim=1)
        mkq = torch.bmm(self.m, sm)
        v_norm = F.normalize(self.v)
        res = torch.bmm(mkq, v_norm)
        return res.squeeze(1)

In [20]:
num_rows = 20
num_cols = 3
num_tok = 4
n_nodes = num_rows + num_cols + num_tok
dim_emb = 12
batch_size = 4
head_number = num_cols

In [73]:
k = torch.ones((num_cols, num_cols))
q = torch.zeros((num_cols, num_cols)).normal_()
v = torch.empty(batch_size, num_cols,  dim_emb).normal_()


In [74]:
v_norm = F.normalize(v)
for head in range(1):
    weights = torch.nn.Softmax(dim=0)(torch.matmul(k[head], q))
    m = torch.ones(num_cols)
    m[head] = 0
    weights = torch.mul(weights, m)
    context_vector = torch.matmul(weights, v)


In [75]:
weights = torch.nn.Softmax(dim=0)(torch.matmul(k[head], q))
weights

tensor([0.0137, 0.6277, 0.3586])

In [76]:
torch.mul(m, weights)

tensor([0.0000, 0.6277, 0.3586])

In [77]:
context_vector

tensor([[-1.0020, -0.2344, -0.1492, -0.8972,  0.6227,  1.4303, -0.1199, -0.8199,
          0.0911,  0.5948,  0.7349, -0.8255],
        [ 0.0902,  0.5959, -0.4133,  1.2431,  0.4643, -0.3567,  0.2688, -0.1477,
          0.0307, -0.2530, -0.4103, -0.7421],
        [ 0.6542,  1.3031, -0.0615, -0.0502, -0.5023,  0.3153,  1.2706, -0.4926,
          0.7535,  0.0381,  0.2997, -0.4056],
        [ 0.6793, -0.0234, -0.3701, -0.0131,  0.0238,  0.9076, -0.0194, -0.6491,
          0.2089, -0.2606, -0.2858,  1.0482]])